@startuml

title __NURINTERFACEFACTORY's Class Diagram__\n

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.NURInterfaceFactory {
        class System.InterfaceFactories.NURInterfaceFactory.NURAddPatient {
            - file : String
            + NURAddPatient()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.NURInterfaceFactory {
        class System.InterfaceFactories.NURInterfaceFactory.NURDefault {
            - file : String
            + NURDefault()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.NURInterfaceFactory {
        class System.InterfaceFactories.NURInterfaceFactory.NURFactory {
            + getInterface()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.NURInterfaceFactory {
        interface System.InterfaceFactories.NURInterfaceFactory.NURInterface {
            {abstract} + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.NURInterfaceFactory {
        class System.InterfaceFactories.NURInterfaceFactory.NURMonitoring {
            - file : String
            + NURMonitoring()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.NURInterfaceFactory {
        class System.InterfaceFactories.NURInterfaceFactory.NURSearch {
            - file : String
            + NURSearch()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.NURInterfaceFactory {
        class System.InterfaceFactories.NURInterfaceFactory.NURSearchResult {
            - file : String
            + NURSearchResult()
            + getFile()
        }
      }
    }
  }
  

  System.InterfaceFactories.NURInterfaceFactory.NURAddPatient .up.|> System.InterfaceFactories.NURInterfaceFactory.NURInterface
  System.InterfaceFactories.NURInterfaceFactory.NURDefault .up.|> System.InterfaceFactories.NURInterfaceFactory.NURInterface
  System.InterfaceFactories.NURInterfaceFactory.NURMonitoring .up.|> System.InterfaceFactories.NURInterfaceFactory.NURInterface
  System.InterfaceFactories.NURInterfaceFactory.NURSearch .up.|> System.InterfaceFactories.NURInterfaceFactory.NURInterface
  System.InterfaceFactories.NURInterfaceFactory.NURSearchResult .up.|> System.InterfaceFactories.NURInterfaceFactory.NURInterface


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
