@startuml

title __DOCINTERFACEFACTORY's Class Diagram__\n

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.DOCInterfaceFactory {
        class System.InterfaceFactories.DOCInterfaceFactory.DOCAddPrescription {
            - file : String
            + DOCAddPrescription()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.DOCInterfaceFactory {
        class System.InterfaceFactories.DOCInterfaceFactory.DOCDefault {
            - file : String
            + DOCDefault()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.DOCInterfaceFactory {
        class System.InterfaceFactories.DOCInterfaceFactory.DOCFactory {
            + getInterface()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.DOCInterfaceFactory {
        interface System.InterfaceFactories.DOCInterfaceFactory.DOCInterface {
            {abstract} + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.DOCInterfaceFactory {
        class System.InterfaceFactories.DOCInterfaceFactory.DOCMonitoring {
            - file : String
            + DOCMonitoring()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.DOCInterfaceFactory {
        class System.InterfaceFactories.DOCInterfaceFactory.DOCSearch {
            - file : String
            + DOCSearch()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.DOCInterfaceFactory {
        class System.InterfaceFactories.DOCInterfaceFactory.DOCSearchResult {
            - file : String
            + DOCSearchResult()
            + getFile()
        }
      }
    }
  }
  

  System.InterfaceFactories.DOCInterfaceFactory.DOCAddPrescription .up.|> System.InterfaceFactories.DOCInterfaceFactory.DOCInterface
  System.InterfaceFactories.DOCInterfaceFactory.DOCDefault .up.|> System.InterfaceFactories.DOCInterfaceFactory.DOCInterface
  System.InterfaceFactories.DOCInterfaceFactory.DOCMonitoring .up.|> System.InterfaceFactories.DOCInterfaceFactory.DOCInterface
  System.InterfaceFactories.DOCInterfaceFactory.DOCSearch .up.|> System.InterfaceFactories.DOCInterfaceFactory.DOCInterface
  System.InterfaceFactories.DOCInterfaceFactory.DOCSearchResult .up.|> System.InterfaceFactories.DOCInterfaceFactory.DOCInterface


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
