@startuml

title __HPINTERFACEFACTORY's Class Diagram__\n

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.HPInterfaceFactory {
        class System.InterfaceFactories.HPInterfaceFactory.HPDismiss {
            - file : String
            + HPDismiss()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.HPInterfaceFactory {
        class System.InterfaceFactories.HPInterfaceFactory.HPFactory {
            + getHPInterface()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.HPInterfaceFactory {
        interface System.InterfaceFactories.HPInterfaceFactory.HPInterface {
            {abstract} + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.HPInterfaceFactory {
        class System.InterfaceFactories.HPInterfaceFactory.HPMonitoring {
            - file : String
            + HPMonitoring()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.HPInterfaceFactory {
        class System.InterfaceFactories.HPInterfaceFactory.HPSearch {
            - file : String
            + HPSearch()
            + getFile()
        }
      }
    }
  }
  

  namespace  {
    namespace ystem {
      namespace InterfaceFactories.HPInterfaceFactory {
        class System.InterfaceFactories.HPInterfaceFactory.HPSearchResult {
            - file : String
            + HPSearchResult()
            + getFile()
        }
      }
    }
  }
  

  System.InterfaceFactories.HPInterfaceFactory.HPDismiss .up.|> System.InterfaceFactories.HPInterfaceFactory.HPInterface
  System.InterfaceFactories.HPInterfaceFactory.HPMonitoring .up.|> System.InterfaceFactories.HPInterfaceFactory.HPInterface
  System.InterfaceFactories.HPInterfaceFactory.HPSearch .up.|> System.InterfaceFactories.HPInterfaceFactory.HPInterface
  System.InterfaceFactories.HPInterfaceFactory.HPSearchResult .up.|> System.InterfaceFactories.HPInterfaceFactory.HPInterface


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
